# platform :ios, '9.0'
target 'Aliexpress' do
  pod 'Alamofire', '~> 4.8.1'
  pod 'Sourcery', '~> 0.15.0'
  pod 'SwiftGen', '~> 6.0.2'
  pod 'Kingfisher', '~> 5.1'
  pod 'SwiftLint', '~> 0.30.0'

  target 'AliexpressTests' do
    pod 'Sourcery', '~> 0.15.0'
    pod 'Nimble', '~> 7.3'
  end

  target 'AliexpressUITests' do
    inherit! :search_paths
  end

end
